[versions]
agp = "8.8.2"
material = "1.12.0"
provider = "13.1.5"
api = "13.1.5"

[libraries]
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
provider = { group = "dev.rikka.shizuku", name = "provider", version.ref = "provider" }
api = { group = "dev.rikka.shizuku", name = "api", version.ref = "api" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

